# α9α10 Allosteric Pharmacophore
# Derived from SAR + IFP + pocket geometry
# Generated by lean_pipeline/phase15_pharmacophore/build_pharmacophore.py

# Load receptor
load ../../02_receptor/a9a10_2to3_apo.pdb, receptor

# Colour scheme
util.cbow 'alpha9', 'blue'
util.cbow 'alpha10', 'orange'
set_color hbd, [0.0, 0.0, 1.0]
set_color hba, [1.0, 0.0, 0.0]
set_color hyd, [0.0, 0.7, 0.0]
set_color neg, [1.0, 1.0, 0.0]
set_color pol, [0.0, 1.0, 1.0]
set_color forb, [0.5, 0.0, 0.5]

# Style
hide everything
show cartoon, receptor
color gray80, receptor
set transparency, 0.3, receptor

# HBD1: Hydroxyl group on ascorbate ring O1
sele HBD1_alpha9_176, resi 176 and chain A
show spheres, HBD1_alpha9_176
color hbd, HBD1_alpha9_176
set sphere_scale, 0.5, HBD1_alpha9_176
label HBD1_alpha9_176 and name CA, 'HBD alpha9:176'
set label_size, 14, HBD1_alpha9_176

sele HBD1_alpha9_175, resi 175 and chain A
show spheres, HBD1_alpha9_175
color hbd, HBD1_alpha9_175
set sphere_scale, 0.5, HBD1_alpha9_175
label HBD1_alpha9_175 and name CA, 'HBD alpha9:175'
set label_size, 14, HBD1_alpha9_175

# HBA1: Carbonyl oxygen of ascorbate lactone
sele HBA1_alpha9_120, resi 120 and chain A
show spheres, HBA1_alpha9_120
color hba, HBA1_alpha9_120
set sphere_scale, 0.5, HBA1_alpha9_120
label HBA1_alpha9_120 and name CA, 'HBA alpha9:120'
set label_size, 14, HBA1_alpha9_120

sele HBA1_alpha10_81, resi 81 and chain D
show spheres, HBA1_alpha10_81
color hba, HBA1_alpha10_81
set sphere_scale, 0.5, HBA1_alpha10_81
label HBA1_alpha10_81 and name CA, 'HBA alpha10:81'
set label_size, 14, HBA1_alpha10_81

# HYD1: C4-C5 region of ascorbate ring
sele HYD1_alpha9_224, resi 224 and chain A
show spheres, HYD1_alpha9_224
color hyd, HYD1_alpha9_224
set sphere_scale, 0.5, HYD1_alpha9_224
label HYD1_alpha9_224 and name CA, 'HYD alpha9:224'
set label_size, 14, HYD1_alpha9_224

sele HYD1_alpha9_217, resi 217 and chain A
show spheres, HYD1_alpha9_217
color hyd, HYD1_alpha9_217
set sphere_scale, 0.5, HYD1_alpha9_217
label HYD1_alpha9_217 and name CA, 'HYD alpha9:217'
set label_size, 14, HYD1_alpha9_217

# NEG1: Carboxylate of ascorbate (anionic form)
sele NEG1_alpha10_143, resi 143 and chain D
show spheres, NEG1_alpha10_143
color neg, NEG1_alpha10_143
set sphere_scale, 0.5, NEG1_alpha10_143
label NEG1_alpha10_143 and name CA, 'NEG alpha10:143'
set label_size, 14, NEG1_alpha10_143

sele NEG1_alpha10_145, resi 145 and chain D
show spheres, NEG1_alpha10_145
color neg, NEG1_alpha10_145
set sphere_scale, 0.5, NEG1_alpha10_145
label NEG1_alpha10_145 and name CA, 'NEG alpha10:145'
set label_size, 14, NEG1_alpha10_145

# POL1: Hydroxymethyl group of ascorbate
sele POL1_alpha9_57, resi 57 and chain A
show spheres, POL1_alpha9_57
color pol, POL1_alpha9_57
set sphere_scale, 0.5, POL1_alpha9_57
label POL1_alpha9_57 and name CA, 'POL alpha9:57'
set label_size, 14, POL1_alpha9_57

sele POL1_alpha9_55, resi 55 and chain A
show spheres, POL1_alpha9_55
color pol, POL1_alpha9_55
set sphere_scale, 0.5, POL1_alpha9_55
label POL1_alpha9_55 and name CA, 'POL alpha9:55'
set label_size, 14, POL1_alpha9_55

# Forbidden regions (steric clashes)
sele forbidden_alpha10_273, resi 273 and chain D
show spheres, forbidden_alpha10_273
color forb, forbidden_alpha10_273
set sphere_scale, 0.3, forbidden_alpha10_273

sele forbidden_alpha9_274, resi 274 and chain A
show spheres, forbidden_alpha9_274
color forb, forbidden_alpha9_274
set sphere_scale, 0.3, forbidden_alpha9_274

# Pharmacophore distances
distance HBD1_HBA1, resi 176 and chain A and name CA, resi 120 and chain A and name CA, 3.2
distance HBD1_HYD1, resi 176 and chain A and name CA, resi 224 and chain A and name CA, 3.2
distance HBD1_NEG1, resi 176 and chain A and name CA, resi 143 and chain D and name CA, 3.2
distance HBD1_POL1, resi 176 and chain A and name CA, resi 57 and chain A and name CA, 3.2
distance HBA1_HYD1, resi 120 and chain A and name CA, resi 224 and chain A and name CA, 2.8
distance HBA1_NEG1, resi 120 and chain A and name CA, resi 143 and chain D and name CA, 2.8
distance HBA1_POL1, resi 120 and chain A and name CA, resi 57 and chain A and name CA, 2.8
distance HYD1_NEG1, resi 224 and chain A and name CA, resi 143 and chain D and name CA, 4.0
distance HYD1_POL1, resi 224 and chain A and name CA, resi 57 and chain A and name CA, 4.0
distance NEG1_POL1, resi 143 and chain D and name CA, resi 57 and chain A and name CA, 3.5

# View
bg_color white
set ray_opaque_background, 0
center receptor
zoom receptor
set_view (\
     1.0000000,    0.0000000,    0.0000000,\
     0.0000000,    1.0000000,    0.0000000,\
     0.0000000,    0.0000000,    1.0000000,\
     0.0000000,    0.0000000, -200.0000000,\
   -50.0000000,   50.0000000,  200.0000000,\
   -10.0000000,  410.0000000,  -10.0000000 )

# Legend
cmd.extend('legend', lambda: None)

