#!/usr/bin/env python3
"""Phase V — Ensemble docking template.

Provides the framework for docking ligands into candidate pockets
using the receptor ensemble. Actual docking requires AutoDock Vina
or similar software.
"""

import csv, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT  = Path(__file__).resolve().parent

# Docking configuration template
DOCKING_CONFIG = {
    "receptor_sources": [
        "phase02_receptor/selected_ensemble.csv",
    ],
    "ligand_sources": [
        "phase01_sar/sar_dataset.csv",
    ],
    "candidate_pockets": "phase03_pockets/",
    "docking_software": "AutoDock Vina",
    "exhaustiveness": 32,
    "num_modes": 10,
    "energy_range": 3,
    "seeds": [1, 2, 3, 4, 5],
    "box_padding_A": 10,
}

def generate_docking_scripts():
    """Generate shell scripts for batch docking."""
    scripts = []
    
    # Template for Vina docking
    vina_template = """#!/bin/bash
# AutoDock Vina docking script
# Generated by lean_pipeline/phase05_docking/generate_docking.py

RECEPTOR={receptor}
LIGAND={ligand}
CENTER_X={center_x}
CENTER_Y={center_y}
CENTER_Z={center_z}
SIZE_X={size_x}
SIZE_Y={size_y}
SIZE_Z={size_z}
OUTPUT={output}

vina \\
    --receptor "$RECEPTOR" \\
    --ligand "$LIGAND" \\
    --center_x "$CENTER_X" \\
    --center_y "$CENTER_Y" \\
    --center_z "$CENTER_Z" \\
    --size_x "$SIZE_X" \\
    --size_y "$SIZE_Y" \\
    --size_z "$SIZE_Z" \\
    --exhaustiveness {exhaustiveness} \\
    --num_modes {num_modes} \\
    --energy_range {energy_range} \\
    --out "$OUTPUT"
"""
    
    return vina_template

def write_config_template(path):
    """Write docking configuration template."""
    lines = [
        "# Docking configuration template",
        "# Edit receptor, ligand, and pocket paths as needed",
        "",
        "receptor: path/to/receptor.pdb",
        "ligand: path/to/ligand.pdbqt",
        "center_x: 0.0",
        "center_y: 0.0",
        "center_z: 0.0",
        "size_x: 20",
        "size_y: 20",
        "size_z: 20",
        "exhaustiveness: 32",
        "num_modes: 10",
        "energy_range: 3",
    ]
    
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")

def write_summary(path):
    lines = [
        "ENSEMBLE DOCKING FRAMEWORK",
        "=" * 60,
        "",
        "This phase requires AutoDock Vina or similar docking software.",
        "",
        "Steps:",
        "1. Prepare receptor PDBQT files from phase02_receptor/selected_ensemble.csv",
        "2. Prepare ligand PDBQT files from phase01_sar/sar_dataset.csv",
        "3. Define docking boxes around candidate pockets from phase03_pockets/",
        "4. Run docking with multiple seeds (5 seeds recommended)",
        "5. Cluster poses by RMSD",
        "6. Prioritize recurring sites, poses, and contacts",
        "",
        "Expected outputs:",
        "  docking_results.csv — all docking poses with scores",
        "  docking_clusters.csv — clustered poses by site",
        "  docking_summary.txt — human-readable summary",
        "",
        "Computational cost:",
        "  ~100 ligands × 5 pockets × 5 seeds = 2,500 docking jobs",
        "  ~2 min per job on CPU = ~83 hours total",
        "  GPU acceleration available with AutoDock-GPU",
    ]
    
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")

def main():
    print("Generating docking configuration...")
    write_config_template(OUT / "docking_template.txt")
    write_summary(OUT / "docking_summary.txt")
    
    print("Done. Edit docking_template.txt and run Vina manually.")
    print("See docking_summary.txt for instructions.")

if __name__ == "__main__":
    main()
